version: '2.1'
services:
  mysql:
    build: ./dockerfiles/db
    volumes:
      - "./data/db:/var/lib/mysql"
      - "./config/db/mariadb.conf.d:/etc/mysql/mariadb.conf.d/"
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 1
  phpfpm:
    depends_on:
      - mysql
    volumes:
      - "./site:/var/www/html:Z"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    restart: unless-stopped
    build: ./dockerfiles/php-fpm
    extra_hosts:
      - "wp-docker-bedrock.dev:172.18.0.1"
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - "./site:/var/www/html:Z"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped
